// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJWb62COFWkuobwJ-bKyIcsKe8VVjjOcU',
    appId: '1:172733934153:web:2d2b1ff0dfc3e5d090ed98',
    messagingSenderId: '172733934153',
    projectId: 'attendance-app-b7b66',
    authDomain: 'attendance-app-b7b66.firebaseapp.com',
    storageBucket: 'attendance-app-b7b66.appspot.com',
    measurementId: 'G-YDTV7Y4DRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg7W_VJq4Ugo6cyOtMKfKEkBXRVSmJDR8',
    appId: '1:172733934153:android:84403c764dcb74c190ed98',
    messagingSenderId: '172733934153',
    projectId: 'attendance-app-b7b66',
    storageBucket: 'attendance-app-b7b66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGF_04UvfBVgWxm-1eeL56S2JpJXLWzag',
    appId: '1:172733934153:ios:4369f0c7c00c45d390ed98',
    messagingSenderId: '172733934153',
    projectId: 'attendance-app-b7b66',
    storageBucket: 'attendance-app-b7b66.appspot.com',
    iosBundleId: 'com.example.ngoLoanApp',
  );
}
